/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppHomeworkRouteImport } from './routes/app.homework'
import { Route as AppNoticesRouteImport } from './routes/app.notices'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSubmissionsRouteImport } from './routes/app.submissions'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppAiContentLibraryRouteImport } from './routes/app.ai.content-library'
import { Route as AppAiStudioRouteImport } from './routes/app.ai.studio'
import { Route as AppAiTeacherAssistantRouteImport } from './routes/app.ai.teacher-assistant'
import { Route as AppAiTutorRouteImport } from './routes/app.ai.tutor'
import { Route as AppPortalParentRouteImport } from './routes/app.portal.parent'
import { Route as AppPortalStaffRouteImport } from './routes/app.portal.staff'
import { Route as AppPortalStudentRouteImport } from './routes/app.portal.student'
import { Route as AppPortalTeacherRouteImport } from './routes/app.portal.teacher'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkRoute = AppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppAiContentLibraryRoute = AppAiContentLibraryRouteImport.update({
  id: '/ai/content-library',
  path: '/ai/content-library',
  getParentRoute: () => AppRoute,
} as any)
const AppAiStudioRoute = AppAiStudioRouteImport.update({
  id: '/ai/studio',
  path: '/ai/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTeacherAssistantRoute = AppAiTeacherAssistantRouteImport.update({
  id: '/ai/teacher-assistant',
  path: '/ai/teacher-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTutorRoute = AppAiTutorRouteImport.update({
  id: '/ai/tutor',
  path: '/ai/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalParentRoute = AppPortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalStaffRoute = AppPortalStaffRouteImport.update({
  id: '/portal/staff',
  path: '/portal/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalStudentRoute = AppPortalStudentRouteImport.update({
  id: '/portal/student',
  path: '/portal/student',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalTeacherRoute = AppPortalTeacherRouteImport.update({
  id: '/portal/teacher',
  path: '/portal/teacher',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/app/$': typeof AppSplatRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit': typeof AppAuditRoute
  '/app/chat': typeof AppChatRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
  '/app/ai/content-library': typeof AppAiContentLibraryRoute
  '/app/ai/studio': typeof AppAiStudioRoute
  '/app/ai/teacher-assistant': typeof AppAiTeacherAssistantRoute
  '/app/ai/tutor': typeof AppAiTutorRoute
  '/app/portal/parent': typeof AppPortalParentRoute
  '/app/portal/staff': typeof AppPortalStaffRoute
  '/app/portal/student': typeof AppPortalStudentRoute
  '/app/portal/teacher': typeof AppPortalTeacherRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/app/$': typeof AppSplatRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit': typeof AppAuditRoute
  '/app/chat': typeof AppChatRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app': typeof AppIndexRoute
  '/app/ai/content-library': typeof AppAiContentLibraryRoute
  '/app/ai/studio': typeof AppAiStudioRoute
  '/app/ai/teacher-assistant': typeof AppAiTeacherAssistantRoute
  '/app/ai/tutor': typeof AppAiTutorRoute
  '/app/portal/parent': typeof AppPortalParentRoute
  '/app/portal/staff': typeof AppPortalStaffRoute
  '/app/portal/student': typeof AppPortalStudentRoute
  '/app/portal/teacher': typeof AppPortalTeacherRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/app/$': typeof AppSplatRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit': typeof AppAuditRoute
  '/app/chat': typeof AppChatRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
  '/app/ai/content-library': typeof AppAiContentLibraryRoute
  '/app/ai/studio': typeof AppAiStudioRoute
  '/app/ai/teacher-assistant': typeof AppAiTeacherAssistantRoute
  '/app/ai/tutor': typeof AppAiTutorRoute
  '/app/portal/parent': typeof AppPortalParentRoute
  '/app/portal/staff': typeof AppPortalStaffRoute
  '/app/portal/student': typeof AppPortalStudentRoute
  '/app/portal/teacher': typeof AppPortalTeacherRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/register'
    | '/app/$'
    | '/app/attendance'
    | '/app/audit'
    | '/app/chat'
    | '/app/homework'
    | '/app/notices'
    | '/app/notifications'
    | '/app/settings'
    | '/app/students'
    | '/app/submissions'
    | '/app/subscription'
    | '/app/'
    | '/app/ai/content-library'
    | '/app/ai/studio'
    | '/app/ai/teacher-assistant'
    | '/app/ai/tutor'
    | '/app/portal/parent'
    | '/app/portal/staff'
    | '/app/portal/student'
    | '/app/portal/teacher'
    | '/app/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/register'
    | '/app/$'
    | '/app/attendance'
    | '/app/audit'
    | '/app/chat'
    | '/app/homework'
    | '/app/notices'
    | '/app/notifications'
    | '/app/settings'
    | '/app/students'
    | '/app/submissions'
    | '/app/subscription'
    | '/app'
    | '/app/ai/content-library'
    | '/app/ai/studio'
    | '/app/ai/teacher-assistant'
    | '/app/ai/tutor'
    | '/app/portal/parent'
    | '/app/portal/staff'
    | '/app/portal/student'
    | '/app/portal/teacher'
    | '/app/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/register'
    | '/app/$'
    | '/app/attendance'
    | '/app/audit'
    | '/app/chat'
    | '/app/homework'
    | '/app/notices'
    | '/app/notifications'
    | '/app/settings'
    | '/app/students'
    | '/app/submissions'
    | '/app/subscription'
    | '/app/'
    | '/app/ai/content-library'
    | '/app/ai/studio'
    | '/app/ai/teacher-assistant'
    | '/app/ai/tutor'
    | '/app/portal/parent'
    | '/app/portal/staff'
    | '/app/portal/student'
    | '/app/portal/teacher'
    | '/app/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/homework': {
      id: '/app/homework'
      path: '/homework'
      fullPath: '/app/homework'
      preLoaderRoute: typeof AppHomeworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notices': {
      id: '/app/notices'
      path: '/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai/content-library': {
      id: '/app/ai/content-library'
      path: '/ai/content-library'
      fullPath: '/app/ai/content-library'
      preLoaderRoute: typeof AppAiContentLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai/studio': {
      id: '/app/ai/studio'
      path: '/ai/studio'
      fullPath: '/app/ai/studio'
      preLoaderRoute: typeof AppAiStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai/teacher-assistant': {
      id: '/app/ai/teacher-assistant'
      path: '/ai/teacher-assistant'
      fullPath: '/app/ai/teacher-assistant'
      preLoaderRoute: typeof AppAiTeacherAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai/tutor': {
      id: '/app/ai/tutor'
      path: '/ai/tutor'
      fullPath: '/app/ai/tutor'
      preLoaderRoute: typeof AppAiTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal/parent': {
      id: '/app/portal/parent'
      path: '/portal/parent'
      fullPath: '/app/portal/parent'
      preLoaderRoute: typeof AppPortalParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal/staff': {
      id: '/app/portal/staff'
      path: '/portal/staff'
      fullPath: '/app/portal/staff'
      preLoaderRoute: typeof AppPortalStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal/student': {
      id: '/app/portal/student'
      path: '/portal/student'
      fullPath: '/app/portal/student'
      preLoaderRoute: typeof AppPortalStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal/teacher': {
      id: '/app/portal/teacher'
      path: '/portal/teacher'
      fullPath: '/app/portal/teacher'
      preLoaderRoute: typeof AppPortalTeacherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditRoute: typeof AppAuditRoute
  AppChatRoute: typeof AppChatRoute
  AppHomeworkRoute: typeof AppHomeworkRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAiContentLibraryRoute: typeof AppAiContentLibraryRoute
  AppAiStudioRoute: typeof AppAiStudioRoute
  AppAiTeacherAssistantRoute: typeof AppAiTeacherAssistantRoute
  AppAiTutorRoute: typeof AppAiTutorRoute
  AppPortalParentRoute: typeof AppPortalParentRoute
  AppPortalStaffRoute: typeof AppPortalStaffRoute
  AppPortalStudentRoute: typeof AppPortalStudentRoute
  AppPortalTeacherRoute: typeof AppPortalTeacherRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditRoute: AppAuditRoute,
  AppChatRoute: AppChatRoute,
  AppHomeworkRoute: AppHomeworkRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
  AppAiContentLibraryRoute: AppAiContentLibraryRoute,
  AppAiStudioRoute: AppAiStudioRoute,
  AppAiTeacherAssistantRoute: AppAiTeacherAssistantRoute,
  AppAiTutorRoute: AppAiTutorRoute,
  AppPortalParentRoute: AppPortalParentRoute,
  AppPortalStaffRoute: AppPortalStaffRoute,
  AppPortalStudentRoute: AppPortalStudentRoute,
  AppPortalTeacherRoute: AppPortalTeacherRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
