/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppHomeworkRouteImport } from './routes/app.homework'
import { Route as AppNoticesRouteImport } from './routes/app.notices'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSubmissionsRouteImport } from './routes/app.submissions'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkRoute = AppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/app/$': typeof AppSplatRoute
  '/app/chat': typeof AppChatRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/app/$': typeof AppSplatRoute
  '/app/chat': typeof AppChatRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app': typeof AppIndexRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/app/$': typeof AppSplatRoute
  '/app/chat': typeof AppChatRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/pricing'
    | '/app/$'
    | '/app/chat'
    | '/app/homework'
    | '/app/notices'
    | '/app/notifications'
    | '/app/settings'
    | '/app/students'
    | '/app/submissions'
    | '/app/subscription'
    | '/app/'
    | '/app/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/app/$'
    | '/app/chat'
    | '/app/homework'
    | '/app/notices'
    | '/app/notifications'
    | '/app/settings'
    | '/app/students'
    | '/app/submissions'
    | '/app/subscription'
    | '/app'
    | '/app/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/pricing'
    | '/app/$'
    | '/app/chat'
    | '/app/homework'
    | '/app/notices'
    | '/app/notifications'
    | '/app/settings'
    | '/app/students'
    | '/app/submissions'
    | '/app/subscription'
    | '/app/'
    | '/app/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/homework': {
      id: '/app/homework'
      path: '/homework'
      fullPath: '/app/homework'
      preLoaderRoute: typeof AppHomeworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notices': {
      id: '/app/notices'
      path: '/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppChatRoute: typeof AppChatRoute
  AppHomeworkRoute: typeof AppHomeworkRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppChatRoute: AppChatRoute,
  AppHomeworkRoute: AppHomeworkRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
